### List new channels
GET {{host}}/v1/channels?members=Davie52&createdAfter=1651867065155
Accept: application/json

### Create a channel
POST {{host}}/v1/channels
Accept: application/json
Content-Type: application/json

{
  "name": "Small Talks",
  "members": [
    "Davie52",
    "Neo",
    "xGamer5000"
  ]
}

### List messages
GET {{host}}/v1/channels/f7a470e6-446e-44c8-af03-2ff89f03a4e3/messages?sentBefore=1651930347028
Accept: application/json

### Send a message 
POST {{host}}/v1/channels/f7a470e6-446e-44c8-af03-2ff89f03a4e3/messages
Accept: application/json
Content-Type: application/json

{
  "author": "Davie52",
  "content": "Hello World!9"
}

### Download a file
GET {{host}}/v1/channels/6aafbddf-187f-453e-b922-45833262e430/files/images.zip
Accept: */*

### Send a file
POST {{host}}/v1/channels/6aafbddf-187f-453e-b922-45833262e430/files
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="hello_world.txt"

Hello World!

--boundary--
