### List new channels
GET {{host}}/v1/channels?members=pawel&createdAfter=1651867065155
Accept: application/json
Authorization: Pawel

### Create a channel
POST {{host}}/v1/channels
Accept: application/json
Content-Type: application/json
Authorization: Pawel

{
  "name": "Small Talks",
  "members": [
    "Davie52",
    "Damian",
    "Pawel"
  ]
}

### List messages
GET {{host}}/v1/channels/467738a3-782d-4c43-90e0-9c30f7c74b48/messages?sentBefore=1652039820413
Accept: application/json
Authorization: Pawel

### Send a message 
POST {{host}}/v1/channels/467738a3-782d-4c43-90e0-9c30f7c74b48/messages
Accept: application/json
Content-Type: application/json
Authorization: Pawel

{
  "author": "Pawel",
  "content": "Hello World!"
}

### Download a file
GET {{host}}/v1/channels/7a778132-a9c2-4ac4-a7da-488f5815191c/files/hello_world.txt
Accept: */*
Authorization: Pawel

### Send a file
POST {{host}}/v1/channels/7a778132-a9c2-4ac4-a7da-488f5815191c/files
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary
Authorization: Pawel

--boundary
Content-Disposition: form-data; name="file"; filename="hello_world.txt"

Hello World!

--boundary--
